version: '3'
services:
#  mysql:
#    image: 'mysql:latest'
#    ports:
#      - 3306:3306
#    environment:
#      - MYSQL_DATABASE=gorm
#      - MYSQL_USER=gorm
#      - MYSQL_PASSWORD=gorm
#      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
#  redis:
#    image: 'redis:latest'
#    ports:
#      - 6379:6379
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.101.65:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

volumes:
  redis-data:
