global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'seckill'
    static_configs:
      - targets: ['192.168.237.1:8080']  # 你的秒杀服务地址

  - job_name: 'redis'
    static_configs:
      - targets: ['192.168.237.1:9121']  # Redis exporter

  - job_name: 'mysql'
    static_configs:
      - targets: ['192.168.237.1:9104']  # MySQL exporter
