{
 "title": "seckill",
 "time": { "from": "2025-07-13T05:54:17.225Z", "to": "2025-07-13T06:44:44.109Z" },
 "panels": [
  {
   "title": "秒杀系统总请求数（QPS）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(seckill_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "成功率（基于业务指标）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(seckill_requests_total{code=~\"2..\"}[5m]))\r\n/\r\nsum(rate(seckill_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "错误率最高的端点",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "\r\ntopk(3, \r\n  sum by (path) (\r\n    rate(http_requests_total{status_code!~\"2..\"}[5m])\r\n  ) \r\n  / \r\n  sum by (path) (\r\n    rate(http_requests_total[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "秒杀请求成功/限流/失败数量比例",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(code) (rate(seckill_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "按端点分类的请求量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (path) (rate(http_requests_total[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "秒杀业务处理流转状态",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(status) (rate(seckill_business_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99响应时间（秒）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "\r\nhistogram_quantile(0.99, \r\n  sum by (le, method, url) (\r\n    rate(seckill_request_duration_seconds_bucket[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "系统内存占用",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "P95响应时间（秒）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "\r\nhistogram_quantile(0.95, \r\n  sum by (le, method, url) (\r\n    rate(seckill_request_duration_seconds_bucket[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "限流请求数量（按优先级）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(priority) (rate(seckill_rate_limited_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "平均响应时间（秒）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "\r\navg(rate(seckill_request_duration_seconds_sum[5m]) / rate(seckill_request_duration_seconds_count[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "平均请求耗时（200状态，秒）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(seckill_request_duration_seconds_sum{code=\"200\"}[1m]) \r\n/\r\nrate(seckill_request_duration_seconds_count{code=\"200\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "请求耗时分布，0.1s 延迟以下请求比例",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(seckill_request_duration_seconds_bucket{le=\"0.1\"}[1m])) \r\n/\r\nsum(rate(seckill_request_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}